spring:
  application:
    name: api-getway
server:
  port: 5555
  
#set routes use url
#zuul:
#  routes:
#    api-a-url:
#      path: /api-a-url/**
#      url: http://10.5.2.241:2222/
#    api-b-url:
#      path: /api-b-url/**
#      url: http://10.5.2.241:2223/
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.5.2.241:1111/eureka/
      
# set routes use serviceId
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: compute-serviceA
    api-b:
      path: /api-b/**
      serviceId: compute-serviceB
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.5.2.241:1111/eureka/   
